package com.mayur.prreviewer.service;

import com.mayur.prreviewer.domain.ChangedFile;
import com.mayur.prreviewer.domain.ChangedFileType;
import com.mayur.prreviewer.domain.DiffHunk;
import com.mayur.prreviewer.domain.ReviewContext;
import com.mayur.prreviewer.git.GitClient;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.IntStream;

public class ContextBuilderService {

    private static final Pattern CLASS_PATTERN = Pattern.compile("\\bclass\\s+(\\w+)");
    private static final Pattern METHOD_PATTERN = Pattern.compile("(public|private|protected)?\\s*(static\\s+)?[\\w<>\\[\\]]+\\s+(\\w+)\\s*\\([^;]*\\)\\s*\\{?");

    private final GitClient gitClient;

    public ContextBuilderService(GitClient gitClient) {
        this.gitClient = gitClient;
    }

    // Builds file or hunk-level review context from the current code.
    public List<ReviewContext> build(Path repositoryRoot, List<ChangedFile> changedFiles, int surroundingLines) {
        List<ReviewContext> contexts = new ArrayList<>();

        for (ChangedFile file : changedFiles) {
            if (file.type() == ChangedFileType.DELETED_FILE) {
                continue;
            }

            String content = gitClient.readFile(repositoryRoot, file.path());
            List<String> lines = Arrays.asList(content.split("\\R", -1));
            boolean generatedCode = isGenerated(content);
            List<String> imports = lines.stream()
                    .filter(line -> line.startsWith("import "))
                    .toList();

            if (file.type() == ChangedFileType.NEW_FILE) {
                contexts.add(new ReviewContext(
                        file.path(),
                        file.type(),
                        findClassName(lines, 1),
                        findMethodName(lines, 1),
                        imports,
                        1,
                        lines.size(),
                        content,
                        generatedCode
                ));
                continue;
            }

            for (DiffHunk hunk : file.hunks()) {
                int startLine = Math.max(1, hunk.newStart() - surroundingLines);
                int endLine = Math.min(lines.size(), hunk.newStart() + Math.max(hunk.newCount(), 1) + surroundingLines);
                String snippet = IntStream.rangeClosed(startLine, endLine)
                        .mapToObj(index -> String.format(Locale.ROOT, "%4d | %s", index, lines.get(index - 1)))
                        .reduce((left, right) -> left + System.lineSeparator() + right)
                        .orElse("");

                contexts.add(new ReviewContext(
                        file.path(),
                        file.type(),
                        findClassName(lines, startLine),
                        findMethodName(lines, startLine),
                        imports,
                        startLine,
                        endLine,
                        snippet,
                        generatedCode
                ));
            }
        }

        return contexts;
    }

    // Detects code that is likely generated and not worth reviewing.
    private boolean isGenerated(String content) {
        String normalized = content.toLowerCase(Locale.ROOT);
        return normalized.contains("@generated")
                || normalized.contains("generated by")
                || normalized.contains("do not edit");
    }

    // Finds the nearest enclosing class name for a code region.
    private String findClassName(List<String> lines, int anchorLine) {
        for (int index = Math.max(0, anchorLine - 1); index >= 0; index--) {
            Matcher matcher = CLASS_PATTERN.matcher(lines.get(index));
            if (matcher.find()) {
                return matcher.group(1);
            }
        }
        return "UnknownClass";
    }

    // Finds the nearest enclosing method name for a code region.
    private String findMethodName(List<String> lines, int anchorLine) {
        for (int index = Math.max(0, anchorLine - 1); index >= 0; index--) {
            Matcher matcher = METHOD_PATTERN.matcher(lines.get(index).trim());
            if (matcher.find()) {
                return matcher.group(3);
            }
        }
        return "UnknownMethod";
    }
}
